export enum EnvVarEnum {
	NODE_ENV = "VITE_NODE_ENV",

	API_BASE_URL = "VITE_API_BASE_URL",

	GOOGLE_CLIENT_ID = "GOOGLE_CLIENT_ID",
	GOOGLE_CLIENT_SECRET = "GOOGLE_CLIENT_SECRET",
	GOOGLE_CALLBACK_URL = "GOOGLE_CALLBACK_URL"
}
